#!/usr/bin/env ruby

def verbose(command)
  puts "--> #{command}"
  system(command) || fail("Failed: #{command}")
end
verbose('npm install jslint') if !system('which jslint')
verbose('./compare_ref_js')
verbose('jslint --bitwise --indent 2 --maxlen 80 index-stp.js')
