#!/usr/bin/env ruby

Dir.chdir(File.expand_path(File.dirname(__FILE__)))

def verbose(command)
  system(command) || (fail "Failed: #{command}")
end

verbose 'c++ -o Reference Reference.cpp'
verbose './Reference'
verbose 'rm -f ./Reference'
